/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myErc20Sol from "./MyERC20.sol";
export type { myErc20Sol };
import type * as myErc21Sol from "./MyERC21.sol";
export type { myErc21Sol };
export type { TokenSale } from "./TokenSale";
