/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as myErc20Sol from "./MyERC20.sol";
export * as myErc21Sol from "./MyERC21.sol";
export { TokenSale__factory } from "./TokenSale__factory";
